name: Build Docker images

on:
  workflow_run:
    workflows: ["Determine updated images"]
    types:
      - completed

jobs:
  build-deploy-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.get-new-images.outputs.changed_images) }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          push: ${{ github.event.workflow_run.branch == 'main' }}
          tags: ghcr.io/${{ github.repository }}:${{ matrix.image }}
